platform :ios, '7.0'

####  数据请求，数据解析  ####
pod 'NSObjectExtend',               '~> 1.5.0' # NS系列类添加常用方法
pod 'AFNetworking',                 '~> 2.5.0' # Http网络请求

####  其他著名开源 ####
pod 'pop',                          '~> 1.0.0' # facebook 开源动画引擎
pod 'SVProgressHUD',                '~> 1.1.0' # 等待指示
pod 'ReactiveCocoa',                '~> 2.5.0' # 响应式编程框架
pod 'BlocksKit',                    '~> 2.2.0' # The Objective-C block utilities you always wish you had.
#pod 'IQKeyboardManager',            '~> 3.2.0' # 防止键盘挡住输入框, 引入项目即可生效
pod 'SDWebImage',                   '~> 3.7.0' # 图片加载器，自动缓存图片
pod 'hpple',                        '~> 0.2.0' # HTML解析器